### ISSUE TITLE
不同手机不同机型部分不好使

### ISSUE THREAD

**Issue by jintiegang** [dxsdyhm/AlarmAndJob#3]
vivo x7 自启动跳转不到、电池跳转正常
vivo x20 自启动跳转正常、电池跳转不到
一加手机无法跳转
坚果手机都无法跳转

**Comment by jintiegang** [comment]
请问大佬有不同手机跳转到开启锁屏通知和悬浮通知页面的方法么？

**Comment by dxsdyhm** [comment]
@jintiegang 这种页面基本国产都有不同的页面，如果你要适配大多数，就需要收集这些手机的页面路径（包名），类似于本例源代码中的页面跳转路径
* 方法，拿到手机后，手动点击到对应要代码跳转的页面，使用ADB指令，dunmp页面栈信息，得到路径后，用intent跳转

**Comment by dxsdyhm** [comment]
@jintiegang 
* 对于vivo部分功能不可用，可能是不同版本的手机路径不同，需要补充新路径，也可能是这些版本本身就没有这个功能，需要具体手机具体分析，手上样机有限，不能写全
* 后面两款手机我手上没有，如果你有，可以按照源码，用上面的方法补全后补充进来，非常感谢
